### ISSUE TITLE
Error occurring on VPS installation

### ISSUE THREAD

**Issue by Dryrtan** [Mosasauroidea/GazellePW#14]
![Error](https://i.ibb.co/t4QSMFY/Screenshot-1.png)
Hello, I'm trying to do the first installation of GazellePW on a VPS. This error is occurring, I figured it could be a problem with the VPS, I tried to install it on another VPS, but the same error occurred. What am I doing wrong? How can I resolve this?

**Comment by Dryrtan** [comment]
I closed it, because after opening it, I noticed that I already had a question and a solution to the problem.

**Comment by IITuxtmuxII** [comment]
what was the solution? nor runing it as root?

**Comment by Dryrtan** [comment]
> what was the solution? nor runing it as root?

No, in my case it was the project permissions https://github.com/Mosasauroidea/GazellePW/issues/2#issuecomment-1146546129
