### ISSUE TITLE
安装的问题

### ISSUE THREAD

**Issue by ljwwz** [Mosasauroidea/GazellePW#17]
我用docker试了很多次都是安装不上的，能不能用其他方法安装或者再写的详细一点那个安装方法

**Comment by 120318** [comment]
你需要详细描述你所遇到的问题，并附上你的错误信息。

**Comment by ljwwz** [comment]
![Uploading Screenshot_20220803_005915.jpg…]()

**Comment by ljwwz** [comment]
Docker 和 Docker Compose我已经安装好了的，然后我就在ssh上运行第一句就报错了，直接安装不了，我输入运行那里第一行docker build -t gpw-web:latest .
就提示 unable to prepare context : unable to evaluate Symlinks in Dockerfile path :1stat/ root / Dockerfile : no such file or directory，这样子提示的

**Comment by 120318** [comment]
看起来是找不到dockerfile，你确认你是项目目录下运行的么。

**Comment by 120318** [comment]
安装教程已经更新。
