### ISSUE TITLE
根据教程，安装出现报错

### ISSUE THREAD

**Issue by GuiMoYan** [Mosasauroidea/GazellePW#22]
教程第一步，docker和docker compose已安装
然后我新建了一个gpw的路径，准备在路径下运行第二个步骤的命令
接着出现报错
[root@centos-2gb-fsn1-1 gpw]# docker build -t gpw-web:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/docker/gpw/Dockerfile: no such file or directory

求助，我应该怎么解决这个问题

**Comment by getupbuzz** [comment]
Duplicate #2

**Comment by 120318** [comment]
检查下 `/home/docker/gpw/Dockerfile`是否存在，以及权限是否有问题。

**Comment by 120318** [comment]
Duplicate of #17

**Comment by GuiMoYan** [comment]
> 检查下 `/home/docker/gpw/Dockerfile`是否存在，以及权限是否有问题。
Dockerfile 这个文件是不存在的，然后我手动创建了一下这个文件夹，也是不行。
[root@centos-2gb-fsn1-1 gpw]# docker build -t gpw-web:latest .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/docker/gpw/Dockerfile: no such file or directory
[root@centos-2gb-fsn1-1 gpw]# mkdir Dockerfile
[root@centos-2gb-fsn1-1 gpw]# docker build -t gpw-web:latest .
Sending build context to Docker daemon 1.536 kB
Error response from daemon: No image was generated. Is your Dockerfile empty?

**Comment by 120318** [comment]
你需要在项目文件夹下执行命令。
