### ISSUE TITLE
运行docker-compose -p gazelle up 报错

### ISSUE THREAD

**Issue by GuiMoYan** [Mosasauroidea/GazellePW#23]
系统  centos7
[root@centos-2gb-fsn1-1 GazellePW]# docker-compose -v
docker-compose version 1.18.0, build 8dd22a9
[root@centos-2gb-fsn1-1 GazellePW]# docker -v
Docker version 1.13.1, build 7d71120/1.13.1

项目文件已经给777权限
根据教程，前面一切成功，然后运行命令 docker-compose -p gazelle up之后报错
[root@centos-2gb-fsn1-1 GazellePW]# docker-compose -p gazelle up
Creating gpw-memcached ... done
Creating gpw-mysql ... 

ERROR: for gpw-mysql  Cannot create container for service mysql: invalid bind mount spec "/home/docker/GazellePW/.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf:delegated": invalid mode: delegated

ERROR: for mysql  Cannot create container for service mysql: invalid bind mount spec "/home/docker/GazellePW/.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf:delegated": inva

**Comment by 120318** [comment]
你的docker版本太低，需要升级。
