### ISSUE TITLE
gpw-mysql Index column size too large

### ISSUE THREAD

**Issue by stephendolan2017** [Mosasauroidea/GazellePW#32]
I'm getting the following error message when trying to start GazellePW for the first time.

gpw-mysql ERROR 1709 (HY000) at line 201: Index column size too large. The maximum column size is 767 bytes

I'm running Ubuntu Server 18.04.6 LTS
Docker version 20.10.17, build 100c70180f
docker-compose version 1.29.2

**Comment by stephendolan2017** [comment]
Full log:


Creating volume "gazelle_node-modules" with default driver
Creating volume "gazelle_mysql-data" with default driver
Creating volume "gazelle_manticore-data" with default driver
Creating gpw-mysql ... 
Creating gpw-memcached ... 
Creating gpw-memcached
Creating gpw-mysql ... done
Creating gpw-web ... 
Creating gpw-phpmyadmin ... 
Creating gpw-web
Creating gpw-web ... done
Creating gpw-manticoresearch ... 
Creating gpw-manticoresearch ... done
Attaching to gpw-memcached, gpw-mysql, gpw-phpmyadmin, gpw-web, gpw-manticoresearch
gpw-mysql          | 2022-10-18 12:11:51+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.3.36+maria~ubu2004 started.
gpw-mysql          | 2022-10-18 12:11:51+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
gpw-phpmyadmin     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
gpw-mysql          | 2022-10-18 12:11:51+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.3.36+maria~ubu2004 started.
gpw-phpmyadmin     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
gpw-web            | ====== Composer Install ======
gpw-web            | Composer version 2.4.3 2022-10-14 16:56:41
gpw-mysql          | 2022-10-18 12:11:52+00:00 [Note] [Entrypoint]: Initializing database files
gpw-web            | Installing dependencies from lock file (including require-dev)
gpw-phpmyadmin     | [Tue Oct 18 12:11:53.481421 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.0.19 configured -- resuming normal operations
gpw-web            | Verifying lock file contents can be installed on current platform.
gpw-phpmyadmin     | [Tue Oct 18 12:11:53.481585 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
gpw-mysql          | 
gpw-web            | Nothing to install, update or remove
gpw-mysql          | 
gpw-mysql          | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
gpw-web            | Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
gpw-mysql          | To do so, start the server, then issue the following command:
gpw-web            | Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
gpw-mysql          | 
gpw-web            | Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
gpw-mysql          | '/usr/bin/mysql_secure_installation'
gpw-web            | Generating autoload files
gpw-mysql          | 
gpw-web            | Carbon 1 is deprecated, see how to migrate to Carbon 2.
gpw-mysql          | which will also give you the option of removing the test
gpw-web            | https://carbon.nesbot.com/docs/#api-carbon-2
gpw-mysql          | databases and anonymous user created by default.  This is
gpw-web            |     You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
gpw-mysql          | strongly recommended for production servers.
gpw-mysql          | 
gpw-web            | 33 packages you are using are looking for funding.
gpw-mysql          | See the MariaDB Knowledgebase at http://mariadb.com/kb
gpw-web            | Use the `composer fund` command to find out more!
gpw-mysql          | 
gpw-mysql          | Please report any problems at http://mariadb.org/jira
gpw-mysql          | 
gpw-web            | 
gpw-mysql          | The latest information about MariaDB is available at http://mariadb.org/.
gpw-mysql          | 
gpw-web            | ====== Yarn Install ======
gpw-mysql          | Consider joining MariaDB's strong and vibrant community:
gpw-mysql          | https://mariadb.org/get-involved/
gpw-mysql          | 
gpw-mysql          | 2022-10-18 12:11:54+00:00 [Note] [Entrypoint]: Database files initialized
gpw-mysql          | 2022-10-18 12:11:54+00:00 [Note] [Entrypoint]: Starting temporary server
gpw-mysql          | 2022-10-18 12:11:54+00:00 [Note] [Entrypoint]: Waiting for server startup
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] mysqld (mysqld 10.3.36-MariaDB-1:10.3.36+maria~ubu2004) starting as process 115 ...
gpw-mysql          | 2022-10-18 12:11:54 0 [Warning] Could not increase number of max_open_files to more than 1024 (request: 6539)
gpw-mysql          | 2022-10-18 12:11:54 0 [Warning] option 'innodb-strict-mode': boolean value '0;' wasn't recognized. Set to OFF.
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Using Linux native AIO
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Uses event mutexes
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Number of pools: 1
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Using generic crc32 instructions
gpw-mysql          | 2022-10-18 12:11:54 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: Completed initialization of buffer pool
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: Creating shared tablespace for temporary tables
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] InnoDB: 10.3.36 started; log sequence number 1625443; transaction id 20
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] Plugin 'FEEDBACK' is disabled.
gpw-mysql          | 2022-10-18 12:11:55 0 [Warning] 'user' entry 'root@3c89bd3ab40f' ignored in --skip-name-resolve mode.
gpw-mysql          | 2022-10-18 12:11:55 0 [Warning] 'proxies_priv' entry '@% root@3c89bd3ab40f' ignored in --skip-name-resolve mode.
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] Reading of all Master_info entries succeeded
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] Added new Master_info '' to hash table
gpw-mysql          | 2022-10-18 12:11:55 0 [Note] mysqld: ready for connections.
gpw-mysql          | Version: '10.3.36-MariaDB-1:10.3.36+maria~ubu2004'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
gpw-mysql          | 2022-10-18 12:11:55+00:00 [Note] [Entrypoint]: Temporary server started.
gpw-web            | yarn install v1.22.19
gpw-web            | [1/4] Resolving packages...
gpw-web            | [2/4] Fetching packages...
gpw-mysql          | 2022-10-18 12:11:59+00:00 [Note] [Entrypoint]: Creating database gazelle
gpw-mysql          | 2022-10-18 12:11:59+00:00 [Note] [Entrypoint]: Creating user gazelle
gpw-mysql          | 2022-10-18 12:11:59+00:00 [Note] [Entrypoint]: Giving user gazelle access to schema gazelle
gpw-mysql          | 2022-10-18 12:11:59+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
gpw-mysql          | 
gpw-mysql          | 2022-10-18 12:11:59+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/gazelle.sql
gpw-mysql          | ERROR 1709 (HY000) at line 201: Index column size too large. The maximum column size is 767 bytes
gpw-mysql exited with code 1

**Comment by 120318** [comment]
fixed.

1. pull the latest code.
2. docker volume remove gpw_mysql-data
3. up docker-compose

**Comment by stephendolan2017** [comment]
That fixed it. However, I'm getting a different error now.

gpw-web            | ====== Yarn Start ======
gpw-web            | Run migrations...
gpw-web            | Phinx by CakePHP - https://phinx.org. 0.10.8
gpw-web            | 
gpw-web            | using config file ./phinx.php
gpw-web            | using config parser php
gpw-web            | using migration paths 
gpw-web            |  - /var/www/db/migrations
gpw-web            | using seed paths 
gpw-web            | warning no environment specified, defaulting to: gazelle
gpw-web            | using adapter mysql
gpw-web            | using database gazelle
gpw-web            | PHP Fatal error:  Cannot declare class TorrentSphinxChecked, because the name is already in use in /var/www/db/migrations/20221017214100_api_rewrite.php on line 5
gpw-web            | PHP Stack trace:
gpw-web            | PHP   1. {main}() /var/www/vendor/bin/phinx:0
gpw-web            | PHP   2. include() /var/www/vendor/bin/phinx:115
gpw-web            | PHP   3. Symfony\Component\Console\Application->run($input = *uninitialized*, $output = *uninitialized*) /var/www/vendor/robmorgan/phinx/bin/phinx:27
gpw-web            | PHP   4. Phinx\Console\PhinxApplication->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:122
gpw-web            | PHP   5. Symfony\Component\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:88
gpw-web            | PHP   6. Symfony\Component\Console\Application->doRunCommand($command = class Phinx\Console\Command\Migrate { protected $config = class Phinx\Config\Config { private $values = [...]; protected $configFilePath = '/var/www/phinx.php' }; protected $adapter = NULL; protected $manager = class Phinx\Migration\Manager { protected $config = class Phinx\Config\Config { ... }; protected $input = class Symfony\Component\Console\Input\ArgvInput { ... }; protected $output = class Symfony\Component\Console\Output\ConsoleOutput { ... }; protected $environments = NULL; protected $migrations = NULL; protected $seeds = NULL }; private ${Symfony\Component\Console\Command\Command}application = class Phinx\Console\PhinxApplication { private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'Phinx by CakePHP - https://phinx.org.'; private ${Symfony\Component\Console\Application}version = '0.10.8'; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = NULL; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = NULL; private ${Symfony\Component\Console\Application}initialized = TRUE }; private ${Symfony\Component\Console\Command\Command}name = 'migrate'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = 'The <info>migrate</info> command runs all available migrations, optionally up to a specific version\n\n<info>phinx migrate -e development</info>\n<info>phinx migrate -e development -t 20110103081132</info>\n<info>phinx migrate -e development -d 20110103</info>\n<info>phinx migrate -e development -v</info>\n'; private ${Symfony\Component\Console\Command\Command}description = 'Migrate the database'; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}applicationDefinitionMerged = TRUE; private ${Symfony\Component\Console\Command\Command}applicationDefinitionMergedWithArgs = TRUE; private ${Symfony\Component\Console\Command\Command}code = NULL; private ${Symfony\Component\Console\Command\Command}synopsis = ['short' => 'migrate [options]', 'long' => 'migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE] [-x|--dry-run] [--fake]']; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:215
gpw-web            | PHP   7. Symfony\Component\Console\Command\Command->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:858
gpw-web            | PHP   8. Phinx\Console\Command\Migrate->execute($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Command/Command.php:240
gpw-web            | PHP   9. Phinx\Migration\Manager->migrate($environment = 'gazelle', $version = NULL, $fake = FALSE) /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php:122
gpw-web            | PHP  10. Phinx\Migration\Manager->getMigrations($environment = 'gazelle') /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:319
gpw-web            | PHP  11. require_once() /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:742
gpw-web            | 
gpw-web            | Fatal error: Cannot declare class TorrentSphinxChecked, because the name is already in use in /var/www/db/migrations/20221017214100_api_rewrite.php on line 5
gpw-web            | 
gpw-web            | Call Stack:
gpw-web            |     0.0011     403208   1. {main}() /var/www/vendor/bin/phinx:0
gpw-web            |     0.0023     405376   2. include('/var/www/vendor/robmorgan/phinx/bin/phinx') /var/www/vendor/bin/phinx:115
gpw-web            |     0.0476    2077416   3. Symfony\Component\Console\Application->run($input = ???, $output = ???) /var/www/vendor/robmorgan/phinx/bin/phinx:27
gpw-web            |     0.0715    2309312   4. Phinx\Console\PhinxApplication->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:122
gpw-web            |     0.0720    2309816   5. Symfony\Component\Console\Application->doRun($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:88
gpw-web            |     0.0725    2310008   6. Symfony\Component\Console\Application->doRunCommand($command = class Phinx\Console\Command\Migrate { protected $config = class Phinx\Config\Config { private $values = [...]; protected $configFilePath = '/var/www/phinx.php' }; protected $adapter = NULL; protected $manager = class Phinx\Migration\Manager { protected $config = class Phinx\Config\Config { ... }; protected $input = class Symfony\Component\Console\Input\ArgvInput { ... }; protected $output = class Symfony\Component\Console\Output\ConsoleOutput { ... }; protected $environments = NULL; protected $migrations = NULL; protected $seeds = NULL }; private ${Symfony\Component\Console\Command\Command}application = class Phinx\Console\PhinxApplication { private ${Symfony\Component\Console\Application}commands = [...]; private ${Symfony\Component\Console\Application}wantHelps = FALSE; private ${Symfony\Component\Console\Application}runningCommand = ...; private ${Symfony\Component\Console\Application}name = 'Phinx by CakePHP - https://phinx.org.'; private ${Symfony\Component\Console\Application}version = '0.10.8'; private ${Symfony\Component\Console\Application}catchExceptions = TRUE; private ${Symfony\Component\Console\Application}autoExit = TRUE; private ${Symfony\Component\Console\Application}definition = class Symfony\Component\Console\Input\InputDefinition { ... }; private ${Symfony\Component\Console\Application}helperSet = class Symfony\Component\Console\Helper\HelperSet { ... }; private ${Symfony\Component\Console\Application}dispatcher = NULL; private ${Symfony\Component\Console\Application}terminal = class Symfony\Component\Console\Terminal { ... }; private ${Symfony\Component\Console\Application}defaultCommand = 'list'; private ${Symfony\Component\Console\Application}singleCommand = NULL; private ${Symfony\Component\Console\Application}initialized = TRUE }; private ${Symfony\Component\Console\Command\Command}name = 'migrate'; private ${Symfony\Component\Console\Command\Command}processTitle = NULL; private ${Symfony\Component\Console\Command\Command}aliases = []; private ${Symfony\Component\Console\Command\Command}definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; private ${Symfony\Component\Console\Command\Command}hidden = FALSE; private ${Symfony\Component\Console\Command\Command}help = 'The <info>migrate</info> command runs all available migrations, optionally up to a specific version\n\n<info>phinx migrate -e development</info>\n<info>phinx migrate -e development -t 20110103081132</info>\n<info>phinx migrate -e development -d 20110103</info>\n<info>phinx migrate -e development -v</info>\n'; private ${Symfony\Component\Console\Command\Command}description = 'Migrate the database'; private ${Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${Symfony\Component\Console\Command\Command}applicationDefinitionMerged = TRUE; private ${Symfony\Component\Console\Command\Command}applicationDefinitionMergedWithArgs = TRUE; private ${Symfony\Component\Console\Command\Command}code = NULL; private ${Symfony\Component\Console\Command\Command}synopsis = ['short' => 'migrate [options]', 'long' => 'migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE] [-x|--dry-run] [--fake]']; private ${Symfony\Component\Console\Command\Command}usages = []; private ${Symfony\Component\Console\Command\Command}helperSet = class Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL } }, $input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:215
gpw-web            |     0.0726    2310008   7. Symfony\Component\Console\Command\Command->run($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Application.php:858
gpw-web            |     0.0732    2315488   8. Phinx\Console\Command\Migrate->execute($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'migrate']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1; private $hasAnArrayArgument = FALSE; private $hasOptional = FALSE; private $options = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = ['command' => 'migrate']; protected $interactive = FALSE }, $output = class Symfony\Component\Console\Output\ConsoleOutput { private $stderr = class Symfony\Component\Console\Output\StreamOutput { private $stream = resource(83) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { ... } }; private ${Symfony\Component\Console\Output\StreamOutput}stream = resource(77) of type (stream); private ${Symfony\Component\Console\Output\Output}verbosity = 32; private ${Symfony\Component\Console\Output\Output}formatter = class Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = FALSE; private $styles = [...]; private $styleStack = class Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } } }) /var/www/vendor/symfony/console/Command/Command.php:240
gpw-web            |     0.1030    2622256   9. Phinx\Migration\Manager->migrate($environment = 'gazelle', $version = NULL, $fake = FALSE) /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php:122
gpw-web            |     0.1030    2622256  10. Phinx\Migration\Manager->getMigrations($environment = 'gazelle') /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:319
gpw-web            |     0.1096    2736968  11. require_once('/var/www/db/migrations/20221017214100_api_rewrite.php') /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:742
gpw-web            | 
gpw-web            | PHINX FAILED TO RUN MIGRATIONS
gpw-web exited with code 1
gpw-manticoresearch | Still waiting for Web (Count: 80).
gpw-manticoresearch | Still waiting for Web (Count: 100).
gpw-manticoresearch | Still waiting for Web (Count: 120).

**Comment by 120318** [comment]
fixed by #34
