### ISSUE TITLE
Wrong link in "Special Thanks" for OPS

### ISSUE THREAD

**Issue by zotabee** [Mosasauroidea/GazellePW#4]
Hello,

In "Special Thanks", https://github.com/Mosasauroidea/GazellePW#special-thanks

For [OPSnet/Gazelle](https://github.com/WhatCD/Gazelle) should be [OPSnet/Gazelle](https://github.com/OPSnet/Gazelle)

And thanks for sharing your great project here!

**Comment by 120318** [comment]
fixed.
