### ISSUE TITLE
修改数据库密码需要改哪些配置？

### ISSUE THREAD

**Issue by else05** [Mosasauroidea/GazellePW#44]
下载了GPW和Ocelot的源码，里面数据库密码是弱密码，我在docker-compose.yml和ocelot.conf中修改了密码进行docker  build ,
GPW 目录下使用docker-compose启动时，web连接数据库失败，mysql日志提示用户认证错误

**Comment by 120318** [comment]
https://github.com/Mosasauroidea/GazellePW/blob/e09fd10508df2ed7907c7163f7f43f8b26a85009/docs/zh-Hans/Getting-Started.md?plain=1#L22
参见此步骤，在`config.local.php`中配置你的`mysql`密码
```
$CONFIG['SQLPASS'] = "password"; //The MySQL password
```
> PS: 你的所有自定义配置都可以写在`config.local.php`中，它会对`config.default.php`的配置进行覆盖。
