### ISSUE TITLE
MediaInfo/BDInfo formatting requirements are too strict

### ISSUE THREAD

**Issue by myselfghost** [Mosasauroidea/GazellePW#51]
MediaInfo/BDInfo formatting requirements are too strict

**Comment by 120318** [comment]
For BDInfo, yes. but I have no better way, because BDInfo has various formats (number of spaces), and I have not found a way to deal with this confusion. If I relax, for some BDInfo, there will be a problem of misidentification

For MediaInfo. Are you currently facing any problems?

**Comment by 120318** [comment]
For this problem, we have made some optimizations.
