### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by ShoyibRatul** [Mosasauroidea/GazellePW#53]
gpw-web            | warning "alias-hq > jscodeshift@0.10.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
gpw-web            | warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
gpw-web            | warning " > postcss-dark-theme-class@0.7.3" has unmet peer dependency "postcss@^8.2.14".
gpw-web            | warning " > remark-extended-table@1.0.1" has unmet peer dependency "remark-parse@^10.0.0".
gpw-web            | warning " > remark-extended-table@1.0.1" has unmet peer dependency "unified@^10.1.0".
gpw-web            | warning "remark-extended-table > mdast-util-extended-table@1.0.1" has unmet peer dependency "mdast-util-gfm-table@^1.0.1".
gpw-web            | warning "remark-extended-table > micromark-extension-extended-table@1.0.1" has unmet peer dependency "micromark@^3.0.5".
gpw-web            | warning "remark-extended-table > micromark-extension-extended-table@1.0.1" has unmet peer dependency "micromark-extension-gfm-table@^1.0.3".
gpw-web            | error Could not write file "/var/www/yarn-error.log": "EACCES: permission denied, open '/var/www/yarn-error.log'"
gpw-web            | error An unexpected error occurred: "EACCES: permission denied, mkdir '/var/www/node_modules'".
gpw-web            | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
gpw-web            | 
gpw-web            | ====== Yarn Start ======
gpw-web            | Run migrations...
gpw-web            | /var/www/.docker/web/entrypoint.sh: line 30: /var/www/vendor/bin/phinx: No such file or directory
gpw-web            | PHINX FAILED TO RUN MIGRATIONS
gpw-web exited with code 1

**Comment by 120318** [comment]
you couldn't run it with root user.

**Comment by thundergreen** [comment]
how would i run it ?? have same issue
