### ISSUE TITLE
what is the default login info for amdin?

### ISSUE THREAD

**Issue by johnsmithodom** [Mosasauroidea/GazellePW#54]
After 

Clone
git clone https://github.com/Mosasauroidea/GazellePW.git
cd GazellePW

Start
docker-compose -p gazelle up 

trying to login as：
user: gazelle
password: password
on 
http://ipv4:9000/

( ! ) Fatal error: Uncaught DB_MYSQL_Exception: MySQL: Invalid Query: INSERT INTO login_attempts (UserID, IP, LastAttempt, Attempts) VALUES ('', '112.9.116.150', '2023-05-31 23:45:17', 1) SQL error: 1364 (Field 'BannedUntil' doesn't have a default value) in /var/www/classes/mysql.class.php on line 199

( ! ) DB_MYSQL_Exception: MySQL: Invalid Query: INSERT INTO login_attempts (UserID, IP, LastAttempt, Attempts) VALUES ('', '112.9.116.150', '2023-05-31 23:45:17', 1) SQL error: 1364 (Field 'BannedUntil' doesn't have a default value) in /var/www/classes/mysql.class.php on line 199

**Comment by 120318** [comment]
which os did you use?

**Comment by johnsmithodom** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by johnsmithodom** [comment]
> which os did you use?

Distributor ID: Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy

**Comment by johnsmithodom** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

fresh debian has the same errors with same install method of docker.

**Comment by 120318** [comment]
I think it because of mysql's strict mode. I don't know why the mysql config file does no effect. maybe you should look the docker log when docker first up.

**Comment by xslidi** [comment]
Change permissions of mysqld_sql_mode.cnf to 0444:

chmod 0444 mysqld_sql_mode.cnf

Then the mysql config could work
