### ISSUE TITLE
php7.4 error Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by baiyou2014** [Mosasauroidea/GazellePW#59]
TORRENT_FORM::head() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:117
TORRENT_FORM::head() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:121
TORRENT_FORM::head() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:153
include() | Undefined variable: GenreTags | /sections/upload/upload.php:167
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:346
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:346
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:346
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:346
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:362
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:371
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:400
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:478
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:518
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:519
TORRENT_FORM::movie_form() | Trying to access array offset on value of type null | /classes/torrent_form.class.php:556

**Comment by 120318** [comment]
These warns may have no impact.
