### ISSUE TITLE
Error when copose

### ISSUE THREAD

**Issue by botsik10** [Mosasauroidea/GazellePW#61]
What i do wrong?Ubuntu20.04

 [3/4] Linking dependencies...
gpw-web              | warning " > highcharts-react-official@3.1.0" has unmet peer dependency "react@>=16.8.0                                                   ".
gpw-web              | warning " > react-resize-detector@7.1.2" has unmet peer dependency "react@^16.0.0 || ^                                                   17.0.0 || ^18.0.0".
gpw-web              | warning " > react-resize-detector@7.1.2" has unmet peer dependency "react-dom@^16.0.0                                                    || ^17.0.0 || ^18.0.0".
gpw-web              | warning " > @mdx-js/react@2.1.5" has unmet peer dependency "react@>=16".
gpw-web              | warning " > @mdx-js/rollup@2.1.5" has unmet peer dependency "rollup@>=2".
gpw-web              | warning " > @preact/preset-vite@2.4.0" has unmet peer dependency "@babel/core@7.x".
gpw-web              | warning "@preact/preset-vite > @babel/plugin-transform-react-jsx@7.19.0" has unmet pee                                                   r dependency "@babel/core@^7.0.0-0".
gpw-web              | warning "@preact/preset-vite > @babel/plugin-transform-react-jsx-development@7.18.6" h                                                   as unmet peer dependency "@babel/core@^7.0.0-0".
gpw-web              | warning "@preact/preset-vite > babel-plugin-transform-hook-names@1.0.2" has unmet peer                                                    dependency "@babel/core@^7.12.10".
gpw-web              | warning "@preact/preset-vite > @babel/plugin-transform-react-jsx > @babel/plugin-synta                                                   x-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
gpw-web              | warning " > @rollup/plugin-yaml@3.1.0" has unmet peer dependency "rollup@^1.20.0 || ^2                                                   .0.0".
gpw-web              | warning "@rollup/plugin-yaml > @rollup/pluginutils@3.1.0" has unmet peer dependency "r                                                   ollup@^1.20.0||^2.0.0".
gpw-web              | warning "alias-hq > jscodeshift@0.10.0" has unmet peer dependency "@babel/preset-env@^                                                   7.1.6".
gpw-web              | warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-esli                                                   nt/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.                                                   3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
gpw-web              | warning " > postcss-dark-theme-class@0.7.3" has unmet peer dependency "postcss@^8.2.14                                                   ".
gpw-web              | warning " > remark-extended-table@1.0.1" has unmet peer dependency "remark-parse@^10.0                                                   .0".
gpw-web              | warning " > remark-extended-table@1.0.1" has unmet peer dependency "unified@^10.1.0".
gpw-web              | warning "remark-extended-table > mdast-util-extended-table@1.0.1" has unmet peer depen                                                   dency "mdast-util-gfm-table@^1.0.1".
gpw-web              | warning "remark-extended-table > micromark-extension-extended-table@1.0.1" has unmet p                                                   eer dependency "micromark@^3.0.5".
gpw-web              | warning "remark-extended-table > micromark-extension-extended-table@1.0.1" has unmet p                                                   eer dependency "micromark-extension-gfm-table@^1.0.3".
gpw-web              | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this comman                                                   d.
gpw-web              | error Could not write file "/var/www/yarn-error.log": "EACCES: permission denied, open                                                    '/var/www/yarn-error.log'"
gpw-web              | error An unexpected error occurred: "EACCES: permission denied, mkdir '/var/www/node_m                                                   odules'".
gpw-web              |
gpw-web              | ====== Yarn Start ======
gpw-web              | Run migrations...
gpw-web              | /var/www/.docker/web/entrypoint.sh: line 30: /var/www/vendor/bin/phinx: No such file o                                                   r directory
gpw-web              | PHINX FAILED TO RUN MIGRATIONS
gpw-web exited with code 1

**Comment by thundergreen** [comment]
same issue here .. any ideas ?
