### ISSUE TITLE
gwp-web docker-compose Error Migration 

### ISSUE THREAD

**Issue by thundergreen** [Mosasauroidea/GazellePW#62]
First of all thanks for this awesome piece of Software. Unfortunately I am facing some hard Times to get IT running with docker-compose.

gwp-web throws this error. Could you enlighten me what is wrong or what i am doing wrong?

Logs:

<div id="m-329649559512596659" class="mail-message expanded" style="color: rgb(255, 255, 255); font-family: sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline"><div class="mail-message-header spacer" style="height: 136px;"></div><div class="mail-message-content collapsible zoom-normal mail-show-images msg5779173247766832639" style="overflow-wrap: break-word; width: 332.176px; display: block; margin: 15px 0px; user-select: auto;"><div class="clear"><div lang="EN-US" link="#0563C1" vlink="#954F72" style="overflow-wrap: break-word;"><p class="m_5779173247766832639ImprintUniqueID" style="margin: 0cm 0cm 0pt;"></p><p class="m_5779173247766832639ImprintUniqueID" style="margin: 0cm 0cm 0pt;"></p><div class="m_5779173247766832639WordSection1"><p class="MsoNormal" align="center" style="text-align: center;"><b><span style="font-size: 18pt; font-family: &quot;Lucida Console&quot;; color: black;">gpw-web<u></u><u></u></span></b></p>
date | stream | content
-- | -- | --
2023/11/20 07:43:28 | stdout | PHINX FAILED TO RUN MIGRATIONS
2023/11/20 07:43:28 | stdout | #24 {main}
2023/11/20 07:43:28 | stdout | #23 /var/www/vendor/bin/phinx(115): include('/var/www/vendor...')
2023/11/20 07:43:28 | stdout | #22 /var/www/vendor/robmorgan/phinx/bin/phinx(27): Symfony\Component\Console\Application->run()
2023/11/20 07:43:28 | stdout | #21 /var/www/vendor/symfony/console/Application.php(122): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 07:43:28 | stdout | #20 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 07:43:28 | stdout | #19 /var/www/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 07:43:28 | stdout | #18 /var/www/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 07:43:28 | stdout | #17 /var/www/vendor/symfony/console/Command/Command.php(240): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 07:43:28 | stdout | #16 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20221213123708, false)
2023/11/20 07:43:28 | stdout | #15 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(365): Phinx\Migration\Manager->executeMigration('gazelle', Object(ArtistRefactor), 'up', false)
2023/11/20 07:43:28 | stdout | #14 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(391): Phinx\Migration\Manager\Environment->executeMigration(Object(ArtistRefactor), 'up', false)
2023/11/20 07:43:28 | stdout | #13 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): ArtistRefactor->change()
2023/11/20 07:43:28 | stdout | #12 /var/www/db/migrations/20220807045951_artist_refactor.php(41): Phinx\Db\Table->save()
2023/11/20 07:43:28 | stdout | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(685): Phinx\Db\Table->update()
2023/11/20 07:43:28 | stdout | #10 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(626): Phinx\Db\Table->executeActions(true)
2023/11/20 07:43:28 | stdout | #9 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(719): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
2023/11/20 07:43:28 | stdout | #8 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(147): Cake\Collection\Collection->each(Object(Closure))
2023/11/20 07:43:28 | stdout | #7 /var/www/vendor/cakephp/collection/CollectionTrait.php(64): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 0)
2023/11/20 07:43:28 | stdout | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 07:43:28 | stdout | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 07:43:28 | stdout | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 07:43:28 | stdout | #3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(931): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('artists_group', Object(Phinx\Db\Util\AlterInstructions))
2023/11/20 07:43:28 | stdout | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(572): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `ar...', Array)
2023/11/20 07:43:28 | stdout | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `ar...')
2023/11/20 07:43:28 | stdout | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(167): PDO->exec('ALTER TABLE `ar...')
2023/11/20 07:43:28 | stdout | Stack trace:
2023/11/20 07:43:28 | stdout | PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Body' in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167
2023/11/20 07:43:28 | stdout | == 20220807045951 ArtistRefactor: migrating
2023/11/20 07:43:28 | stdout |  
2023/11/20 07:43:28 | stdout | using database gazelle
2023/11/20 07:43:28 | stdout | using adapter mysql
2023/11/20 07:43:28 | stdout | warning no environment specified, defaulting to: gazelle
2023/11/20 07:43:28 | stdout | using seed paths
2023/11/20 07:43:28 | stdout | - /var/www/db/migrations
2023/11/20 07:43:28 | stdout | using migration paths
2023/11/20 07:43:28 | stdout | using config parser php
2023/11/20 07:43:27 | stdout | using config file ./phinx.php
2023/11/20 07:43:27 | stdout |  
2023/11/20 07:43:27 | stdout | Phinx by CakePHP - https://phinx.org. 0.10.8
2023/11/20 07:43:25 | stdout | Run migrations...
2023/11/20 07:43:25 | stdout | $ vite
2023/11/20 07:43:24 | stdout | yarn run v1.22.19
2023/11/20 07:43:24 | stdout | ====== Yarn Start ======
2023/11/20 07:43:24 | stdout |  
2023/11/20 07:43:24 | stdout | Done in 1.39s.
2023/11/20 07:43:24 | stdout | success Already up-to-date.
2023/11/20 07:43:23 | stdout | [1/4] Resolving packages...
2023/11/20 07:43:23 | stdout | yarn install v1.22.19
2023/11/20 07:43:22 | stdout | ====== Yarn Install ======
2023/11/20 07:43:22 | stdout |  
2023/11/20 07:43:22 | stderr | Use the `composer fund` command to find out more!
2023/11/20 07:43:22 | stderr | 34 packages you are using are looking for funding.
2023/11/20 07:43:22 | stdout | You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
2023/11/20 07:43:22 | stdout | https://carbon.nesbot.com/docs/#api-carbon-2
2023/11/20 07:43:22 | stdout | Carbon 1 is deprecated, see how to migrate to Carbon 2.
2023/11/20 07:43:20 | stderr | Generating autoload files
2023/11/20 07:43:20 | stderr | Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
2023/11/20 07:43:20 | stderr | Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
2023/11/20 07:43:20 | stderr | Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
2023/11/20 07:43:20 | stderr | Nothing to install, update or remove
2023/11/20 07:43:20 | stderr | Verifying lock file contents can be installed on current platform.
2023/11/20 07:43:20 | stderr | Installing dependencies from lock file (including require-dev)
2023/11/20 07:43:19 | stdout | Composer version 2.6.5 2023-10-06 10:11:52
2023/11/20 07:43:14 | stdout | ====== Composer Install ======
2023/11/20 03:22:45 | stdout | PHINX FAILED TO RUN MIGRATIONS
2023/11/20 03:22:43 | stdout | #24 {main}
2023/11/20 03:22:43 | stdout | #23 /var/www/vendor/bin/phinx(115): include('/var/www/vendor...')
2023/11/20 03:22:43 | stdout | #22 /var/www/vendor/robmorgan/phinx/bin/phinx(27): Symfony\Component\Console\Application->run()
2023/11/20 03:22:43 | stdout | #21 /var/www/vendor/symfony/console/Application.php(122): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 03:22:43 | stdout | #20 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 03:22:43 | stdout | #19 /var/www/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 03:22:43 | stdout | #18 /var/www/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 03:22:43 | stdout | #17 /var/www/vendor/symfony/console/Command/Command.php(240): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2023/11/20 03:22:43 | stdout | #16 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20221213123708, false)
2023/11/20 03:22:43 | stdout | #15 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(365): Phinx\Migration\Manager->executeMigration('gazelle', Object(ArtistRefactor), 'up', false)
2023/11/20 03:22:43 | stdout | #14 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(391): Phinx\Migration\Manager\Environment->executeMigration(Object(ArtistRefactor), 'up', false)
2023/11/20 03:22:43 | stdout | #13 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): ArtistRefactor->change()
2023/11/20 03:22:43 | stdout | #12 /var/www/db/migrations/20220807045951_artist_refactor.php(41): Phinx\Db\Table->save()
2023/11/20 03:22:43 | stdout | #11 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(685): Phinx\Db\Table->update()
2023/11/20 03:22:43 | stdout | #10 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(626): Phinx\Db\Table->executeActions(true)
2023/11/20 03:22:43 | stdout | #9 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(719): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
2023/11/20 03:22:43 | stdout | #8 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(147): Cake\Collection\Collection->each(Object(Closure))
2023/11/20 03:22:43 | stdout | #7 /var/www/vendor/cakephp/collection/CollectionTrait.php(64): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 0)
2023/11/20 03:22:43 | stdout | #6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 03:22:43 | stdout | #5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 03:22:43 | stdout | #4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
2023/11/20 03:22:43 | stdout | #3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(931): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('artists_group', Object(Phinx\Db\Util\AlterInstructions))
2023/11/20 03:22:43 | stdout | #2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(572): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `ar...', Array)
2023/11/20 03:22:43 | stdout | #1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `ar...')
2023/11/20 03:22:43 | stdout | #0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(167): PDO->exec('ALTER TABLE `ar...')
2023/11/20 03:22:43 | stdout | Stack trace:
2023/11/20 03:22:42 | stdout | PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Body' in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167
2023/11/20 03:22:39 | stdout | == 20220807045951 ArtistRefactor: migrating
2023/11/20 03:22:39 | stdout |  
2023/11/20 03:22:33 | stdout | using database gazelle
2023/11/20 03:22:33 | stdout | using adapter mysql
2023/11/20 03:22:33 | stdout | warning no environment specified, defaulting to: gazelle
2023/11/20 03:22:33 | stdout | using seed paths
2023/11/20 03:22:33 | stdout | - /var/www/db/migrations
2023/11/20 03:22:33 | stdout | using migration paths
2023/11/20 03:22:33 | stdout | using config parser php
2023/11/20 03:22:30 | stdout | using config file ./phinx.php
2023/11/20 03:22:30 | stdout |  
2023/11/20 03:22:30 | stdout | Phinx by CakePHP - https://phinx.org. 0.10.8
2023/11/20 03:21:40 | stdout | Run migrations...
2023/11/20 03:21:35 | stdout | $ vite
2023/11/20 03:21:35 | stdout | yarn run v1.22.19
2023/11/20 03:21:27 |  

</div><p></p><p></p></div></div></div><div class="mail-message-footer spacer collapsible" style="display: block; height: 43px;"></div></div><br class="Apple-interchange-newline">gpw-web

date

stream

content

2023/11/20 07:43:28

stdout

PHINX FAILED TO RUN MIGRATIONS

2023/11/20 07:43:28

stdout

#24 {main}

2023/11/20 07:43:28

stdout

#23 /var/www/vendor/bin/phinx(115): include('/var/www/vendor...')

2023/11/20 07:43:28

stdout

#22 /var/www/vendor/robmorgan/phinx/bin/phinx(27): Symfony\Component\Console\Application->run()

2023/11/20 07:43:28

stdout

#21 /var/www/vendor/symfony/console/Application.php(122): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 07:43:28

stdout

#20 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 07:43:28

stdout

#19 /var/www/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 07:43:28

stdout

#18 /var/www/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 07:43:28

stdout

#17 /var/www/vendor/symfony/console/Command/Command.php(240): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 07:43:28

stdout

#16 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20221213123708, false)

2023/11/20 07:43:28

stdout

#15 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(365): Phinx\Migration\Manager->executeMigration('gazelle', Object(ArtistRefactor), 'up', false)

2023/11/20 07:43:28

stdout

#14 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(391): Phinx\Migration\Manager\Environment->executeMigration(Object(ArtistRefactor), 'up', false)

2023/11/20 07:43:28

stdout

#13 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): ArtistRefactor->change()

2023/11/20 07:43:28

stdout

#12 /var/www/db/migrations/20220807045951_artist_refactor.php(41): Phinx\Db\Table->save()

2023/11/20 07:43:28

stdout

#11 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(685): Phinx\Db\Table->update()

2023/11/20 07:43:28

stdout

#10 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(626): Phinx\Db\Table->executeActions(true)

2023/11/20 07:43:28

stdout

#9 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(719): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))

2023/11/20 07:43:28

stdout

#8 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(147): Cake\Collection\Collection->each(Object(Closure))

2023/11/20 07:43:28

stdout

#7 /var/www/vendor/cakephp/collection/CollectionTrait.php(64): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 0)

2023/11/20 07:43:28

stdout

#6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 07:43:28

stdout

#5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 07:43:28

stdout

#4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 07:43:28

stdout

#3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(931): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('artists_group', Object(Phinx\Db\Util\AlterInstructions))

2023/11/20 07:43:28

stdout

#2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(572): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `ar...', Array)

2023/11/20 07:43:28

stdout

#1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `ar...')

2023/11/20 07:43:28

stdout

#0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(167): PDO->exec('ALTER TABLE `ar...')

2023/11/20 07:43:28

stdout

Stack trace:

2023/11/20 07:43:28

stdout

PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Body' in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167

2023/11/20 07:43:28

stdout

 == 20220807045951 ArtistRefactor: migrating

2023/11/20 07:43:28

stdout

2023/11/20 07:43:28

stdout

using database gazelle

2023/11/20 07:43:28

stdout

using adapter mysql

2023/11/20 07:43:28

stdout

warning no environment specified, defaulting to: gazelle

2023/11/20 07:43:28

stdout

using seed paths 

2023/11/20 07:43:28

stdout

 - /var/www/db/migrations

2023/11/20 07:43:28

stdout

using migration paths 

2023/11/20 07:43:28

stdout

using config parser php

2023/11/20 07:43:27

stdout

using config file ./phinx.php

2023/11/20 07:43:27

stdout

2023/11/20 07:43:27

stdout

Phinx by CakePHP - https://phinx.org/. 0.10.8

2023/11/20 07:43:25

stdout

Run migrations...

2023/11/20 07:43:25

stdout

$ vite

2023/11/20 07:43:24

stdout

yarn run v1.22.19

2023/11/20 07:43:24

stdout

====== Yarn Start ======

2023/11/20 07:43:24

stdout

2023/11/20 07:43:24

stdout

Done in 1.39s.

2023/11/20 07:43:24

stdout

success Already up-to-date.

2023/11/20 07:43:23

stdout

[1/4] Resolving packages...

2023/11/20 07:43:23

stdout

yarn install v1.22.19

2023/11/20 07:43:22

stdout

====== Yarn Install ======

2023/11/20 07:43:22

stdout

2023/11/20 07:43:22

stderr

Use the `composer fund` command to find out more!

2023/11/20 07:43:22

stderr

34 packages you are using are looking for funding.

2023/11/20 07:43:22

stdout

    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.

2023/11/20 07:43:22

stdout

https://carbon.nesbot.com/docs/#api-carbon-2

2023/11/20 07:43:22

stdout

Carbon 1 is deprecated, see how to migrate to Carbon 2.

2023/11/20 07:43:20

stderr

Generating autoload files

2023/11/20 07:43:20

stderr

Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

2023/11/20 07:43:20

stderr

Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.

2023/11/20 07:43:20

stderr

Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

2023/11/20 07:43:20

stderr

Nothing to install, update or remove

2023/11/20 07:43:20

stderr

Verifying lock file contents can be installed on current platform.

2023/11/20 07:43:20

stderr

Installing dependencies from lock file (including require-dev)

2023/11/20 07:43:19

stdout

Composer version 2.6.5 2023-10-06 10:11:52

2023/11/20 07:43:14

stdout

====== Composer Install ======

2023/11/20 03:22:45

stdout

PHINX FAILED TO RUN MIGRATIONS

2023/11/20 03:22:43

stdout

#24 {main}

2023/11/20 03:22:43

stdout

#23 /var/www/vendor/bin/phinx(115): include('/var/www/vendor...')

2023/11/20 03:22:43

stdout

#22 /var/www/vendor/robmorgan/phinx/bin/phinx(27): Symfony\Component\Console\Application->run()

2023/11/20 03:22:43

stdout

#21 /var/www/vendor/symfony/console/Application.php(122): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 03:22:43

stdout

#20 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 03:22:43

stdout

#19 /var/www/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 03:22:43

stdout

#18 /var/www/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 03:22:43

stdout

#17 /var/www/vendor/symfony/console/Command/Command.php(240): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

2023/11/20 03:22:43

stdout

#16 /var/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('gazelle', 20221213123708, false)

2023/11/20 03:22:43

stdout

#15 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(365): Phinx\Migration\Manager->executeMigration('gazelle', Object(ArtistRefactor), 'up', false)

2023/11/20 03:22:43

stdout

#14 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(391): Phinx\Migration\Manager\Environment->executeMigration(Object(ArtistRefactor), 'up', false)

2023/11/20 03:22:43

stdout

#13 /var/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): ArtistRefactor->change()

2023/11/20 03:22:43

stdout

#12 /var/www/db/migrations/20220807045951_artist_refactor.php(41): Phinx\Db\Table->save()

2023/11/20 03:22:43

stdout

#11 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(685): Phinx\Db\Table->update()

2023/11/20 03:22:43

stdout

#10 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(626): Phinx\Db\Table->executeActions(true)

2023/11/20 03:22:43

stdout

#9 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(719): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))

2023/11/20 03:22:43

stdout

#8 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(147): Cake\Collection\Collection->each(Object(Closure))

2023/11/20 03:22:43

stdout

#7 /var/www/vendor/cakephp/collection/CollectionTrait.php(64): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 0)

2023/11/20 03:22:43

stdout

#6 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 03:22:43

stdout

#5 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 03:22:43

stdout

#4 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)

2023/11/20 03:22:43

stdout

#3 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(931): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('artists_group', Object(Phinx\Db\Util\AlterInstructions))

2023/11/20 03:22:43

stdout

#2 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(572): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `ar...', Array)

2023/11/20 03:22:43

stdout

#1 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `ar...')

2023/11/20 03:22:43

stdout

#0 /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(167): PDO->exec('ALTER TABLE `ar...')

2023/11/20 03:22:43

stdout

Stack trace:

2023/11/20 03:22:42

stdout

PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'Body' in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167

2023/11/20 03:22:39

stdout

 == 20220807045951 ArtistRefactor: migrating

2023/11/20 03:22:39

stdout

2023/11/20 03:22:33

stdout

using database gazelle

2023/11/20 03:22:33

stdout

using adapter mysql

2023/11/20 03:22:33

stdout

warning no environment specified, defaulting to: gazelle

2023/11/20 03:22:33

stdout

using seed paths 

2023/11/20 03:22:33

stdout

 - /var/www/db/migrations

2023/11/20 03:22:33

stdout

using migration paths 

2023/11/20 03:22:33

stdout

using config parser php

2023/11/20 03:22:30

stdout

using config file ./phinx.php

2023/11/20 03:22:30

stdout

2023/11/20 03:22:30

stdout

Phinx by CakePHP - https://phinx.org/. 0.10.8

2023/11/20 03:21:40

stdout

Run migrations...

2023/11/20 03:21:35

stdout

$ vite

2023/11/20 03:21:35

stdout

yarn run v1.22.19

2023/11/20 03:21:27

Your Help would be highly appreciated

Best regards

**Comment by 120318** [comment]
try clear your environment and run again.
