### ISSUE TITLE
没有smtp配置选项，无法发送邮件

### ISSUE THREAD

**Issue by baiyou2014** [Mosasauroidea/GazellePW#7]
config缺少smtp邮件配置选项，只有mailigun的api配置。尝试在phpmail写入smtp配置，发送邮件没提示成功，在个人信息页面，发送风险提示邮件，貌似后面框没有邮件地址可以选择

**Comment by 120318** [comment]
修复了邮件发送中`smtp`的方式，需要在`classes/config.php`中设置`smtp`有关内容。可以参考`config.template.php`的新增配置。
