### ISSUE TITLE
Looking for a converter for XBTIT FM 

### ISSUE THREAD

**Issue by nexus382** [Mosasauroidea/GazellePW#9]
Looking for a converter to bring my site, thesceneplace.com, which runs XBTIT FM 3.1, to this code. I need to bring my user base, and would LOVE to bring my 50 K torrents over too, but the users are a MUST. Can anyone help or point me in the right direction? I LOVE this code, and would like to represent the hard work that has gone in to it, and bring this code to the community.

**Comment by 120318** [comment]
It may be a lot of work. I'm not sure if GazellePW is compatible enough with XBTIT. 
Maybe [xbtitfm-to-unit3d](https://github.com/HDInnovations/xbtitfm-to-unit3d) and [gazelle-to-unit3d](https://github.com/HDInnovations/gazelle-to-unit3d) can help and inspire you.
